# Generated by Django 6.0 on 2026-01-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestquestion',
            name='order',
            field=models.IntegerField(default=0, help_text='Thứ tự câu hỏi'),
        ),
    ]
